version: '3.8'

networks:
  app_network:
    driver: bridge

volumes:
  images:
    driver: local
  logs:
    driver: local
  static:
    driver: local

services:
  app:
    container_name: app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - images:/app/images
      - logs:/app/logs
      - ./static:/app/static
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  nginx:
    container_name: nginx
    command: nginx -g "daemon off;"
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - images:/app/images:ro
      - logs:/var/log/nginx
      - ./static:/app/static:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.2'
          memory: 128M
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 3s
      retries: 3
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped