networks:
  default:

volumes:
  images:
  logs:
  static:

services:
  app:
    container_name: app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - images:/images
      - logs:/logs
      - static:/static
    networks:
      - default

  nginx:
    container_name: nginx
    command: nginx -g "daemon off;"
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - images:/images
      - ./static:/etc/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static/favicon.ico:/static/favicon.ico
#      - ./favicon.ico:/images/favicon.ico
    networks:
      - default
    depends_on:
      - app