networks:
  default:

volumes:
  images:
  logs:
  static:

services:
  app:
    container_name: app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - images:/app/images
      - logs:/logs
      - /Users/pavelnerobov/PycharmProjects/Image_hosting/static:/static  # Абсолютный путь
    networks:
      - default

  nginx:
    container_name: nginx
    command: nginx -g "daemon off;"
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - images:/images  # Исправлено на /images для согласованности
      - /Users/pavelnerobov/PycharmProjects/Image_hosting/static:/static  # Абсолютный путь
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /Users/pavelnerobov/PycharmProjects/Image_hosting/static/favicon.ico:/static/favicon.ico  # Абсолютный путь
    networks:
      - default
    depends_on:
      - app